FROM ubuntu:24.04


########################################################################################################################
# Install Dependencies                                                                                                 #
########################################################################################################################
USER root
RUN <<EOF
    apt-get update
    apt-get -y install g++ cmake git

    # Needed for the dev environment
    apt-get -y install cppcheck flawfinder doxygen graphviz gdb

    # For Drogon:
    apt-get install -y libjsoncpp-dev uuid-dev zlib1g-dev libyaml-cpp-dev libssl-dev
    apt-get install -y libsqlite3-dev
EOF
########################################################################################################################
# Create User                                                                                                          #
########################################################################################################################
# Change root Password to 1234
RUN echo 'root:1234' | chpasswd
# Create new user: "dev"
RUN useradd -ms /bin/bash dev
USER dev